#!/bin/env bash

# Update bootc containers
# SPDX-License-Identifier: MIT
set -eu

# Which PROJECTS should be built?
PROJECTS=()

for project in "${PROJECTS[@]}"; do
	if [[ -f ${HOME}/.ci/build/${project}/.simple-ci/master.conf ]]; then
		buildid=$(date -u +%Y%m%d.%H%M)
		"${HOME}"/.ci/podman/build-podman -p "${project}" \
			-w "${HOME}/.ci/build/${project}" \
			-b "${buildid}" \
			-c "${HOME}/.ci/build/${project}/.simple-ci/master.conf"
	fi
done
