#!/bin/bash

# Update bootc containers
# SPDX-License-Identifier: MIT
set -eu

# Which images should be built?
IMAGES=()

for img in "${IMAGES[@]}"; do
	"${HOME}"/.ci/podman/build-podman -p "${img}" -w "${HOME}"/.ci/build/"${img}" \
		-b "$(date -u +%Y%m%d.%H%M)" -u
done
